# Numpy

-->Numpy is a popular library

-->Numpy is very useful to perform the linear algebra.

-->Numpy supports to perform mathemeatical operations and some basic statistical functions.

-->Numpy library helps us to create a multidimensional arrays.

-->Numpy is memory efficient. 

In [1]:
import numpy as np

In [3]:
#array--->array is a homogenous collection of values

#syntax of array

#np.array()

In [4]:
l1 = [4,7,8,2,10]

In [5]:
l1

[4, 7, 8, 2, 10]

In [6]:
type(l1)

list

In [7]:
#list to array

In [8]:
arr1 = np.array(l1)

In [9]:
arr1

array([ 4,  7,  8,  2, 10])

In [13]:
l2 = [5,7,4,2,9.7,8.9]

In [14]:
arr2 = np.array(l2)

In [15]:
arr2

array([5. , 7. , 4. , 2. , 9.7, 8.9])

1-D array

In [10]:
#np.array([])

In [11]:
a1 = np.array([7,8,5,4,1,9])

In [12]:
a1

array([7, 8, 5, 4, 1, 9])

In [16]:
#Array operations

In [17]:
print("Dimension of the array:",a1.ndim)

Dimension of the array: 1


In [18]:
print("Size of the array:",a1.size)

Size of the array: 6


In [19]:
print("data type of the array values:",a1.dtype)

data type of the array values: int32


In [20]:
arr2

array([5. , 7. , 4. , 2. , 9.7, 8.9])

In [21]:
arr2.dtype

dtype('float64')

In [22]:
l3=[1,5,7,5.2,2.6,'subrat']
l3

[1, 5, 7, 5.2, 2.6, 'subrat']

In [23]:
arr3 = np.array(l3)
arr3

array(['1', '5', '7', '5.2', '2.6', 'subrat'], dtype='<U32')

In [24]:
arr3.dtype

dtype('<U32')

In [25]:
a1

array([7, 8, 5, 4, 1, 9])

In [26]:
print("shape of the array:",a1.shape)    #(size,)

shape of the array: (6,)


2 - D array

In [27]:
#np.array([[]])

In [28]:
a2 = np.array([[5,7,9,3,9]])

In [29]:
a2

array([[5, 7, 9, 3, 9]])

In [30]:
a2.ndim

2

In [31]:
a2.size

5

In [32]:
a2.dtype

dtype('int32')

In [33]:
a3 = np.array([[2,4,5],[6,7,8],[5,6,9]])
a3

array([[2, 4, 5],
       [6, 7, 8],
       [5, 6, 9]])

In [34]:
a3.ndim

2

In [35]:
a3.size

9

In [36]:
a3.shape   #(rows,columns)

(3, 3)

In [37]:
a2

array([[5, 7, 9, 3, 9]])

In [38]:
a2.shape

(1, 5)

In [39]:
a5 = np.array([[4,5,6,7],[7,5,4]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

3 - D array

In [41]:
#np.array([[[]]])

In [53]:
arr1 = np.array([[[4,6,7,3,2,8]]])
arr1

array([[[4, 6, 7, 3, 2, 8]]])

In [43]:
arr.ndim

3

In [44]:
arr2 = np.array([[[3,4,5,6],[6,9,6,5],[6,7,4,3]]])
arr2

array([[[3, 4, 5, 6],
        [6, 9, 6, 5],
        [6, 7, 4, 3]]])

In [45]:
arr2.ndim

3

In [46]:
arr3 = np.array([[[3,4,5,6,6]],[[7,8,5,4,6]]])
arr3

array([[[3, 4, 5, 6, 6]],

       [[7, 8, 5, 4, 6]]])

In [48]:
arr3.ndim

3

In [49]:
arr4 = np.array([[[5,3,5],[7,8,5],[7,6,5]],[[7,8,5],[5,4,3],[2,1,4]]])

In [50]:
arr4

array([[[5, 3, 5],
        [7, 8, 5],
        [7, 6, 5]],

       [[7, 8, 5],
        [5, 4, 3],
        [2, 1, 4]]])

In [51]:
arr4.ndim

3

In [54]:
arr1.shape  #(how many 2D, how many 1D, how many elements individual 1D)

(1, 1, 6)

In [55]:
arr2.shape

(1, 3, 4)

In [56]:
arr3.shape

(2, 1, 5)

In [57]:
arr4.shape

(2, 3, 3)

In [58]:
#array functions

In [60]:
#initialize all the array elements with 0

#np.zeros((shape))

In [61]:
s1 = np.zeros((3,4))   #output float
s1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
s1.ndim

2

In [62]:
s2 = np.zeros((3,4),'int')
s2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [63]:
s3 = np.zeros((4,))
s3

array([0., 0., 0., 0.])

In [66]:
s3.ndim

1

In [64]:
#initialize all the array elements with 1

#np.ones((shape))

In [68]:
s4 = np.ones((3,4,5),'int')
s4

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [69]:
s4.ndim

3

In [70]:
s4.shape

(3, 4, 5)

In [72]:
#initialize all the array elements with any value

#np.full((shape),which value)

In [73]:
s5 = np.full((3,6),50)
s5

array([[50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50]])

In [74]:
s6 = np.full((3,3,5),1000,'float')
s6

array([[[1000., 1000., 1000., 1000., 1000.],
        [1000., 1000., 1000., 1000., 1000.],
        [1000., 1000., 1000., 1000., 1000.]],

       [[1000., 1000., 1000., 1000., 1000.],
        [1000., 1000., 1000., 1000., 1000.],
        [1000., 1000., 1000., 1000., 1000.]],

       [[1000., 1000., 1000., 1000., 1000.],
        [1000., 1000., 1000., 1000., 1000.],
        [1000., 1000., 1000., 1000., 1000.]]])

In [76]:
#np.arange(start,end+1,step+1)

In [77]:
arr4 = np.arange(1,11)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr5 = np.arange(1,11,3)
arr5

array([ 1,  4,  7, 10])

In [2]:
#identity matrix

#np.identity(number,dtype)

In [3]:
arr1 = np.identity(4)
arr1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
arr2 = np.identity(3,'int')
arr2

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

random data


In [7]:
#np.random.random((shape))

In [11]:
a1 = np.random.random((2,3))
a1

array([[0.26686886, 0.7736974 , 0.70759792],
       [0.35668761, 0.38617764, 0.66504104]])

In [12]:
#integer random number

#np.random.randint(start,end,(shape))

In [15]:
a2 = np.random.randint(1,50,(3,4))
a2

array([[41, 29, 19, 23],
       [44,  8, 15, 44],
       [40, 30,  5, 40]])

In [16]:
#float random number within a range

#np.random.uniform(start,end,(shape))

In [17]:
a3 = np.random.uniform(1,100,(3,2,4))
a3

array([[[ 3.04309573, 50.51752579, 82.77062292,  7.3174656 ],
        [99.95824277, 56.55333397, 71.1578169 , 90.71039148]],

       [[19.60447546, 68.59855213, 90.64996328, 85.54403658],
        [73.04524891, 12.15589777, 13.54604355, 61.02970413]],

       [[78.43349592,  2.56079036, 44.09443611, 71.11511964],
        [ 3.52625877, 37.2115671 , 57.81810884, 60.74134072]]])

mathematical functions

In [18]:
arr1 = np.array([2,3,4])
arr2 = np.array([4,5,6])

In [19]:
arr1

array([2, 3, 4])

In [20]:
arr2

array([4, 5, 6])

In [21]:
#np.sum()

In [22]:
np.sum(arr1)

9

In [23]:
np.sum(arr2)

15

In [25]:
np.sum([arr1,arr2])

24

In [26]:
np.sum([arr1,arr2],axis=0)   #axis=0   column-wise

array([ 6,  8, 10])

In [27]:
np.sum([arr1,arr2],axis=1)   #axis=1  row-wise

array([ 9, 15])

In [28]:
arr3 = np.array([[1,2,3],[4,5,6]])

In [29]:
arr4 = np.array([[1,2,4],[5,4,2]])

In [30]:
np.sum([arr3,arr4])

39

In [31]:
np.sum(arr3)

21

In [32]:
np.sum(arr4)

18

In [33]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr4

array([[1, 2, 4],
       [5, 4, 2]])

In [35]:
np.sum([arr3,arr4],axis=1)

array([[5, 7, 9],
       [6, 6, 6]])

In [36]:
np.sum([arr3,arr4],axis=0)

array([[2, 4, 7],
       [9, 9, 8]])

In [37]:
#np.subtract()

In [40]:
arr1

array([2, 3, 4])

In [41]:
arr2

array([4, 5, 6])

In [39]:
np.subtract(arr1,arr2)  #arr1-arr2

array([-2, -2, -2])

In [42]:
np.subtract(arr2,arr1)

array([2, 2, 2])

In [43]:
np.subtract(arr3,arr4)

array([[ 0,  0, -1],
       [-1,  1,  4]])

In [44]:
#multiply

#np.multiply(arr1,arr2)

In [45]:
np.multiply(arr1,arr2)

array([ 8, 15, 24])

In [46]:
np.multiply(arr2,arr1)

array([ 8, 15, 24])

In [47]:
np.multiply(arr3,arr4)

array([[ 1,  4, 12],
       [20, 20, 12]])

In [48]:
#division

In [49]:
#np.divide()

In [50]:
np.divide(arr1,arr2)

array([0.5       , 0.6       , 0.66666667])

In [51]:
np.divide(arr2,arr1)

array([2.        , 1.66666667, 1.5       ])

In [52]:
np.divide(arr3,arr4)

array([[1.  , 1.  , 0.75],
       [0.8 , 1.25, 3.  ]])

In [53]:
#np.floor_divide()    //(operator)

In [54]:
np.floor_divide(arr3,arr4)

array([[1, 1, 0],
       [0, 1, 3]])

In [55]:
np.floor_divide(arr2,arr1)

array([2, 1, 1])

In [56]:
#remainder

In [58]:
#np.mod()

In [61]:
np.mod(arr1,arr2)

array([2, 3, 4])

In [59]:
arr1

array([2, 3, 4])

In [60]:
arr2

array([4, 5, 6])

In [62]:
np.mod(arr2,arr1)

array([0, 2, 2])

In [65]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
arr4

array([[1, 2, 4],
       [5, 4, 2]])

In [64]:
np.mod(arr4,arr3)

array([[0, 0, 1],
       [1, 4, 2]])

In [69]:
arr4 % arr3

array([[0, 0, 1],
       [1, 4, 2]])

In [63]:
np.pi

3.141592653589793

In [67]:
#power   **

In [70]:
3**3

27

In [71]:
np.power(3,3)

27

In [72]:
np.power(2,10)

1024

In [73]:
#square root

In [74]:
#np.sqrt(data)

In [75]:
np.sqrt(1)

1.0

In [76]:
np.sqrt(2)

1.4142135623730951

In [77]:
np.sqrt(arr1)

array([1.41421356, 1.73205081, 2.        ])

In [78]:
#exponential

In [79]:
#e^value    e-2.718

In [80]:
np.exp(1)

2.718281828459045

In [82]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
np.exp(arr3)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [83]:
#log value

In [84]:
np.log(1)

0.0

In [85]:
np.log(10)

2.302585092994046

In [86]:
np.log(arr2)

array([1.38629436, 1.60943791, 1.79175947])

In [87]:
#trignometrics

In [88]:
np.sin(arr1)

array([ 0.90929743,  0.14112001, -0.7568025 ])

In [89]:
np.cos(arr1)

array([-0.41614684, -0.9899925 , -0.65364362])

In [90]:
np.tan(arr1)

array([-2.18503986, -0.14254654,  1.15782128])

In [94]:
#central tendencies

In [95]:
arr = np.array([3,5,7,2,5,3,6,8])

In [96]:
arr

array([3, 5, 7, 2, 5, 3, 6, 8])

In [97]:
np.mean(arr)

4.875

In [98]:
np.median(arr)

5.0

In [99]:
np.sort(arr)

array([2, 3, 3, 5, 5, 6, 7, 8])

In [101]:
np.mode(arr)

AttributeError: module 'numpy' has no attribute 'mode'

In [102]:
np.max(arr)

8

In [103]:
np.min(arr)

2