# Numpy

-->Numpy is a popular library

-->Numpy is very useful to perform the linear algebra.

-->Numpy supports to perform mathemeatical operations and some basic statistical functions.

-->Numpy library helps us to create a multidimensional arrays.

-->Numpy is memory efficient. 

In [2]:
import numpy as np

In [3]:
#array--->array is a homogenous collection of values

#syntax of array

#np.array()

In [4]:
l1 = [4,7,8,2,10]

In [5]:
l1

[4, 7, 8, 2, 10]

In [6]:
type(l1)

list

In [7]:
#list to array

In [8]:
arr1 = np.array(l1)

In [9]:
arr1

array([ 4,  7,  8,  2, 10])

In [13]:
l2 = [5,7,4,2,9.7,8.9]

In [14]:
arr2 = np.array(l2)

In [15]:
arr2

array([5. , 7. , 4. , 2. , 9.7, 8.9])

1-D array

In [10]:
#np.array([])

In [11]:
a1 = np.array([7,8,5,4,1,9])

In [12]:
a1

array([7, 8, 5, 4, 1, 9])

In [16]:
#Array operations

In [17]:
print("Dimension of the array:",a1.ndim)

Dimension of the array: 1


In [18]:
print("Size of the array:",a1.size)

Size of the array: 6


In [19]:
print("data type of the array values:",a1.dtype)

data type of the array values: int32


In [20]:
arr2

array([5. , 7. , 4. , 2. , 9.7, 8.9])

In [21]:
arr2.dtype

dtype('float64')

In [22]:
l3=[1,5,7,5.2,2.6,'subrat']
l3

[1, 5, 7, 5.2, 2.6, 'subrat']

In [23]:
arr3 = np.array(l3)
arr3

array(['1', '5', '7', '5.2', '2.6', 'subrat'], dtype='<U32')

In [24]:
arr3.dtype

dtype('<U32')

In [25]:
a1

array([7, 8, 5, 4, 1, 9])

In [26]:
print("shape of the array:",a1.shape)    #(size,)

shape of the array: (6,)


2 - D array

In [27]:
#np.array([[]])

In [28]:
a2 = np.array([[5,7,9,3,9]])

In [29]:
a2

array([[5, 7, 9, 3, 9]])

In [30]:
a2.ndim

2

In [31]:
a2.size

5

In [32]:
a2.dtype

dtype('int32')

In [33]:
a3 = np.array([[2,4,5],[6,7,8],[5,6,9]])
a3

array([[2, 4, 5],
       [6, 7, 8],
       [5, 6, 9]])

In [34]:
a3.ndim

2

In [35]:
a3.size

9

In [36]:
a3.shape   #(rows,columns)

(3, 3)

In [37]:
a2

array([[5, 7, 9, 3, 9]])

In [38]:
a2.shape

(1, 5)

In [39]:
a5 = np.array([[4,5,6,7],[7,5,4]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

3 - D array

In [41]:
#np.array([[[]]])

In [53]:
arr1 = np.array([[[4,6,7,3,2,8]]])
arr1

array([[[4, 6, 7, 3, 2, 8]]])

In [43]:
arr.ndim

3

In [44]:
arr2 = np.array([[[3,4,5,6],[6,9,6,5],[6,7,4,3]]])
arr2

array([[[3, 4, 5, 6],
        [6, 9, 6, 5],
        [6, 7, 4, 3]]])

In [45]:
arr2.ndim

3

In [46]:
arr3 = np.array([[[3,4,5,6,6]],[[7,8,5,4,6]]])
arr3

array([[[3, 4, 5, 6, 6]],

       [[7, 8, 5, 4, 6]]])

In [48]:
arr3.ndim

3

In [49]:
arr4 = np.array([[[5,3,5],[7,8,5],[7,6,5]],[[7,8,5],[5,4,3],[2,1,4]]])

In [50]:
arr4

array([[[5, 3, 5],
        [7, 8, 5],
        [7, 6, 5]],

       [[7, 8, 5],
        [5, 4, 3],
        [2, 1, 4]]])

In [51]:
arr4.ndim

3

In [54]:
arr1.shape  #(how many 2D, how many 1D, how many elements individual 1D)

(1, 1, 6)

In [55]:
arr2.shape

(1, 3, 4)

In [56]:
arr3.shape

(2, 1, 5)

In [57]:
arr4.shape

(2, 3, 3)

In [58]:
#array functions

In [60]:
#initialize all the array elements with 0

#np.zeros((shape))

In [61]:
s1 = np.zeros((3,4))   #output float
s1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
s1.ndim

2

In [62]:
s2 = np.zeros((3,4),'int')
s2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [63]:
s3 = np.zeros((4,))
s3

array([0., 0., 0., 0.])

In [66]:
s3.ndim

1

In [64]:
#initialize all the array elements with 1

#np.ones((shape))

In [68]:
s4 = np.ones((3,4,5),'int')
s4

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [69]:
s4.ndim

3

In [70]:
s4.shape

(3, 4, 5)

In [72]:
#initialize all the array elements with any value

#np.full((shape),which value)

In [73]:
s5 = np.full((3,6),50)
s5

array([[50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50],
       [50, 50, 50, 50, 50, 50]])

In [74]:
s6 = np.full((3,3,5),1000,'float')
s6

array([[[1000., 1000., 1000., 1000., 1000.],
        [1000., 1000., 1000., 1000., 1000.],
        [1000., 1000., 1000., 1000., 1000.]],

       [[1000., 1000., 1000., 1000., 1000.],
        [1000., 1000., 1000., 1000., 1000.],
        [1000., 1000., 1000., 1000., 1000.]],

       [[1000., 1000., 1000., 1000., 1000.],
        [1000., 1000., 1000., 1000., 1000.],
        [1000., 1000., 1000., 1000., 1000.]]])

In [76]:
#np.arange(start,end+1,step+1)

In [77]:
arr4 = np.arange(1,11)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr5 = np.arange(1,11,3)
arr5

array([ 1,  4,  7, 10])