In [1]:
# Inheritance and Encapsulation

## Polymorphism:

(Many forms)

is a concept of OOP that allows objects of different classes to be treated as objects of common base class.

Advantages: Write more flexible code, Reusable code.

In [4]:
class Shape:
    def area(self):
        pass
    
class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius
        
    def area(self): # Method Overriding
        return 3.14 * self.radius * self.radius
    
class Rectangle(Shape):
    def __init__(self, length, breadth):
        self.length = length
        self.breadth = breadth
        
    def area(self):
        return self.length * self.breadth
    
def calculate_area(shape): # Shows polymorphism
    return shape.area()

c = Circle(2) # Object 1
calculate_area(c)

12.56

In [5]:
rect = Rectangle(4, 6)
calculate_area(rect)

24

### Types of Polymorphism:

1. Compile-time polymorphism (Method Overloading)

2. Runtime polymorphism (Method Overriding)

#### Compile time polymorphism:

We define multiple methods in the same class with same name but with different parameters.

In [6]:
def add(a, b):
    print(a + b)
    
def add(a, b, c): # Method Overloading
    print(a + b + c)
    
add(3, 4, 3)

10


In [7]:
add(5, 2) # Error because python only considers last function definition

TypeError: add() missing 1 required positional argument: 'c'

#### To overcome this issue in Python, we can use Default Parameters:

In [8]:
def add(a, b, c=0): # c is a default paramter set to 0
    print(a + b + c)
    
add(5, 3)

8


In [9]:
add(3, 5, 6)

14


In [10]:
def mult(a=1, b=1,c=1, d=1):
    print(a * b * c * d)
    
mult()

1


In [11]:
mult(4, 5)

20


In [12]:
mult(3, 2, 5)

30


In [13]:
mult(2, 2, 2, 3)

24


In [14]:
def operation(a, b):
    return a + b

def operation(a, b, c, d):
    return a - b - c - d

def operation(a, b, c): # This works
     return a * b * c

In [15]:
operation(3, 4, 5, 5)

TypeError: operation() takes 3 positional arguments but 4 were given

In [16]:
operation(4, 5, 2)

40

In [17]:
class MathOp:
    def add(self, a, b=0, c=0):
        return a + b + c
    
calc = MathOp()

In [18]:
calc.add(2, 3)

5

In [19]:
calc.add(2, 3, 5)

10

In [20]:
calc.add()

TypeError: MathOp.add() missing 1 required positional argument: 'a'

#### Runtime Polymorphism:

Redefining the function in subclass(child) that was already defined in base class.

Overloading: Same func name, different parameters

Overriding: Same func name, different func definition

##### Overloading:

def add(a, b):

def add(a, b, c):

##### Overriding:

def add(a, b):
    return a + b
    
def add(a, b):
    return a - b

In [21]:
class Animal:
    def speak(self):
        print("Animal Speaks")
        
class Dog(Animal):
    def speak(self): # Method Overriding
        print("Dog barks")
        
class Cat(Animal):
    def speak(self): # Method Overriding
        print("Cat meows")
        
def sounds(an): # Takes in object
    return an.speak()

animal = Animal()
sounds(animal)

Animal Speaks


In [22]:
dog = Dog()
sounds(dog)

Dog barks


In [23]:
cat = Cat()
sounds(cat)

Cat meows


#### Uses:

Simplifies code,

Code reusability,

Modularity and Easy to maintain.

## Abstraction:

used to help focus on the relevant or useful information/data by hiding by unnecessary details.

In python, we use abstract class and abstract methods with help of the abc module to implement abstraction.

In [24]:
from abc import ABC, abstractmethod 

# Abstract class
class Shape(ABC): # Shows that Shape is the abstract base class
    @abstractmethod
    def area(self):
        pass
    
# Class implementing abstract class
class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius
        
    def area(self):
        return 3.14 * self.radius * self.radius
    
class Square(Shape):
    def __init__(self, side):
        self.side = side
    
    def area(self):
        return self.side * self.side
    
circle = Circle(2)
circle.area()

12.56

In [25]:
square = Square(5)
square.area()

25

In [26]:
# Example of abstraction layer

In [27]:
import numpy as np

In [28]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [29]:
np.ones(3)

array([1., 1., 1.])

In [30]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q. Create a Python class representing a Book. Include attributes such as title, author, and publication year. Implement a method to display information about the book.

In [32]:
class Book:
    def __init__(self, title, author, pub_year):
        self.t = title
        self.a = author
        self.pub_year = pub_year
        
    def display(self):
        print('Title of book is:', self.t)
        print('Author is:', self.a)
        print('Publication Year is:', self.pub_year)
        
b = Book('Julius Caesar', 'Shakespeare', 1599)
b.display()

Title of book is: Julius Caesar
Author is: Shakespeare
Publication Year is: 1599


In [33]:
age = int(input("Enter age: "))
name = input("Enter name: ")
print(f"My name is {name}, and age is {age}.")

Enter age: 32
Enter name: Max
My name is Max, and age is 32.


Q. Prime number or not. 

Q. Fibonacci Sequence.